[build]
publish = "build/website/"
command = "make"

# Permanent redirect from the netlify domain to the canonical domain
[[redirects]]
from = "https://org-pietroalbini-persuade.netlify.com/*"
to = "https://persuade.pietroalbini.org/:splat"
status = 301
force = true

# Security headers
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Xss-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "no-referrer"
Content-Security-Policy = "default-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline'; font-src * data:; img-src * data:; connect-src *"
